# Copyright 2026 Data Dance s.r.o.
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

from odoo.addons.account.tests.common import AccountTestInvoicingCommon
from odoo.addons.l10n_sk_vat_return.models.res_company import (
    SK_PRE_2025_RC_BAND,
)
from odoo.tests import tagged


@tagged("post_install", "-at_install")
class TestSkHistoricVatRates(AccountTestInvoicingCommon):
    """The Slovak historical rates, and the properties a history import needs.

    Every assertion here corresponds to a way the feature could be silently
    useless: a rate that exists but reports nothing, one that appears when
    raising today's invoice, or one that multiplies on every module upgrade.

    The chart is loaded by the test rather than assumed to be in the database,
    which also exercises the chart-load hook: the rates below are generated by
    ``_load`` during ``setUpClass``, not by an explicit call.
    """

    chart_template = "sk"

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.company = cls.env.company
        cls.Tax = cls.env["account.tax"].with_context(active_test=False)

    def _historic(self, rate=None):
        domain = [
            ("company_id", "=", self.company.id),
            ("cssk_historic_valid_from", "!=", False),
        ]
        if rate is not None:
            domain.append(("amount", "=", rate))
        return self.Tax.search(domain)

    def _current(self, rate):
        return self.Tax.search([
            ("company_id", "=", self.company.id), ("amount", "=", rate),
            ("cssk_historic_valid_from", "=", False),
        ])

    def _settle(self):
        """Generate once, so the set of source taxes is not still moving.

        The accounting test fixture creates a few taxes of its own AFTER the
        chart is loaded, and therefore after the chart-load hook has run. Those
        legitimately have no historical twin yet, so a count or an idempotency
        check taken straight from ``setUpClass`` would be measuring the fixture
        rather than this module. Settling first is what makes the assertions
        about the generator.
        """
        return self.company._cssk_create_historic_vat_taxes()

    def test_loading_the_chart_generates_them(self):
        """Nobody has to remember to ask.

        A migration project's companies are created *after* the modules are
        installed, so a post-install hook alone would have missed exactly the
        companies the feature exists for.
        """
        self.assertTrue(
            self._historic(),
            "loading the Slovak chart should have generated the historical "
            "rates without an explicit call",
        )

    def test_the_whole_family_is_generated_not_just_the_plain_rate(self):
        """A rate is not one tax.

        The Slovak chart carries a dozen taxes at 23 % — reverse charge, EU
        acquisition, triangulation, import, customs, unpaid, and the sale-side
        variants. A history import that only got a plain ``20%`` would fail on
        every § 69(3) service and every intra-EU acquisition in the archive,
        which on a Slovak importer's purchase side is most of it.
        """
        self._settle()
        current = self._current(23.0)
        self.assertTrue(current, "the 23 % family must exist to be cloned from")
        self.assertEqual(
            len(self._historic(20.0)), len(current),
            "every current standard-rate tax needs a 20 % twin, not just the "
            "plain one",
        )
        names = set(self._historic(20.0).mapped("name"))
        self.assertIn("20% RC", names, "§ 69(3) services received")
        self.assertIn("20% EU", names, "§ 49(2)(c) intra-EU acquisitions")

    def test_the_20_percent_reverse_charge_files_on_the_band_that_existed(self):
        """Cloning the tags is right until the form moves the line.

        The reverse-charge band was ONE line, ``r09``/``r10``, until the vzor of
        1. 7. 2025 split it by rate — ``dph2021.xsd`` defines no lettered
        variants and ``dph2025.xsd`` adds four. So a 20 % clone of today's 23 %
        inherits tags ``09b``/``10b``: lines that did not exist while 20 % was
        in force, and it files on them.

        Measured by the MRP extractor against a filed FY2024 return — 804.03 of
        base and 160.81 of tax on r09b where the filing uses r09.

        The domestic bands are genuinely interchangeable (20 % and 23 % supplies
        both file on r03/r04), which is why the clone is right in general and
        wrong exactly here.
        """
        self._settle()
        rc20 = self.Tax.search([
            ("company_id", "=", self.company.id), ("name", "=", "20% RC"),
        ], limit=1)
        self.assertTrue(rc20, "no 20 % reverse-charge tax was generated")
        tags = set(rc20.invoice_repartition_line_ids.tag_ids.mapped("name"))
        self.assertFalse(
            tags & {"09b", "10b"},
            "the 20 %% reverse charge still files on a band that did not "
            "exist when 20 %% was in force: %s" % sorted(tags),
        )
        self.assertTrue(
            tags & {"09", "10"},
            "it must file on the single pre-2025 band instead: %s"
            % sorted(tags),
        )

    def test_the_current_reverse_charge_is_left_alone(self):
        """The remap must not touch the rate the form actually split for."""
        self._settle()
        rc23 = self.Tax.search([
            ("company_id", "=", self.company.id), ("name", "=", "23% RC"),
            ("cssk_historic_valid_from", "=", False),
        ], limit=1)
        self.assertTrue(rc23)
        tags = set(rc23.invoice_repartition_line_ids.tag_ids.mapped("name"))
        self.assertTrue(
            tags & {"09b", "10b"},
            "23 %% is the standard band in the current form and must keep "
            "09b/10b: %s" % sorted(tags),
        )

    def test_a_historic_rate_is_archived(self):
        """It must exist without appearing anywhere somebody raises a document."""
        historic = self._historic()
        self.assertTrue(historic)
        self.assertFalse(
            any(historic.mapped("active")),
            "a rate that is no longer in force must not be selectable for "
            "today's work — that is the whole reason it is safe to ship them",
        )
        self.assertFalse(
            self.env["account.tax"].search([("id", "in", historic.ids)]),
            "and an ordinary search must not return it",
        )

    def test_the_clone_keeps_the_tags_that_make_it_report(self):
        """Tags are the point. A rate with no tags computes and reports nothing.

        Cloning is what carries them: the Slovak return's line numbers are
        rate-agnostic slots — the customer's filed 2024-11 return puts 20 %
        supplies on r03/r04 and the 2025-01 return puts 23 % on the same
        r03/r04, likewise r07/r08 for EU acquisitions and r09/r10 for § 69(3)
        services. So the current tax's tags are the correct tags for the
        historical rate. Measured from filings, not reasoned from the statute.
        """
        self._settle()
        checked = 0
        for tax in self._historic():
            source = tax.cssk_historic_source_tax_id
            self.assertTrue(source, "a generated rate must name what it came from")
            for field in ("invoice_repartition_line_ids",
                          "refund_repartition_line_ids"):
                mine = tax[field].filtered(lambda r: r.repartition_type == "tax")
                theirs = source[field].filtered(
                    lambda r: r.repartition_type == "tax")
                self.assertEqual(
                    len(mine), len(theirs),
                    "%s lost a repartition leg on %s" % (tax.name, field),
                )
                # Tags are cloned EXCEPT where the form moved the line, which
                # for SK is the reverse-charge band: 09b/10b became 09/10
                # before mid-2025. So the test is that every leg carries tags
                # and that any difference is an intended remap, not that the
                # two are identical — asserting identity would forbid the
                # remap that makes a 20 % reverse charge file correctly.
                remap = SK_PRE_2025_RC_BAND
                for got, want in zip(mine, theirs):
                    got_tags = sorted(got.tag_ids.mapped("name"))
                    want_tags = sorted(
                        remap.get(n, n) for n in want.tag_ids.mapped("name"))
                    self.assertEqual(
                        got_tags, want_tags,
                        "%s carries %s where its source implies %s"
                        % (tax.name, got_tags, want_tags),
                    )
                    self.assertTrue(
                        got_tags or not want_tags,
                        "%s lost its tags entirely and would report into no "
                        "line of the return" % tax.name,
                    )
                self.assertEqual(
                    mine.mapped("factor_percent"), theirs.mapped("factor_percent"),
                    "%s changed the repartition split — on a reverse charge "
                    "that is the +100/-100 pair" % tax.name,
                )
            checked += 1
        self.assertTrue(checked, "nothing was actually checked")

    def test_running_twice_creates_nothing_and_clones_no_clones(self):
        """Idempotent, and never a historical twin OF a historical twin."""
        self._settle()
        before = self._historic()
        self._settle()
        after = self._historic()
        self.assertEqual(
            set(before.ids), set(after.ids),
            "a second run duplicated the historical rates — this method runs "
            "on every module upgrade and on every chart load",
        )
        self.assertFalse(
            after.filtered(
                lambda t: t.cssk_historic_source_tax_id.cssk_historic_valid_from
            ),
            "a historical rate was cloned from another historical rate",
        )

    def test_a_hand_made_rate_is_adopted_rather_than_duplicated(self):
        """The state both reference companies were actually in.

        Rates created ad hoc for one import, active and unmarked — four in the
        Slovak company, six in the Czech one. Generating must take them over,
        not leave a second tax with the same name beside them: two
        identical-looking taxes is worse than none, because the mapping picks
        one and the reports read the other.
        """
        self._historic().unlink()
        self.assertFalse(self._historic(), "starting from no generated rates")
        source = self._current(23.0).filtered(
            lambda t: t.type_tax_use == "purchase" and t.name == "23%"
        )[:1]
        self.assertTrue(source, "expected a plain 23 % purchase tax")
        handmade = source.copy({"name": "20%", "amount": 20.0})
        self.assertTrue(handmade.active)

        self.company._cssk_create_historic_vat_taxes()

        same = self.Tax.search([
            ("company_id", "=", self.company.id), ("name", "=", "20%"),
            ("type_tax_use", "=", "purchase"),
        ])
        self.assertEqual(
            same, handmade,
            "the hand-made rate should have been adopted, leaving exactly one "
            "tax with that name",
        )
        self.assertFalse(handmade.active, "and archived with the rest")
        self.assertEqual(handmade.cssk_historic_valid_from.year, 2011)
        self.assertEqual(handmade.cssk_historic_valid_to.year, 2024)
        self.assertEqual(handmade.cssk_historic_source_tax_id, source)

    def test_an_archived_rate_still_posts_and_computes(self):
        """The property the whole feature rests on.

        If Odoo refused an archived tax on a new move line, "archived so it
        does not pollute" and "usable by an importer" would be in direct
        conflict. Tested on the ledger-entry shape an importer actually builds
        — a tax on a plain ``line_ids`` base line — rather than only the
        invoice shape, because that is the path most imported documents take.
        """
        tax = self._historic(20.0).filtered(
            lambda t: t.type_tax_use == "purchase" and t.name == "20%"
        )[:1]
        self.assertTrue(tax, "no plain 20 % purchase tax was generated")
        self.assertFalse(tax.active)

        expense = self.company_data["default_account_expense"]
        payable = self.company_data["default_account_payable"]
        move = self.env["account.move"].with_company(self.company).create({
            "move_type": "entry",
            "journal_id": self.company_data["default_journal_misc"].id,
            "date": "2024-06-30",
            "line_ids": [
                (0, 0, {"account_id": expense.id, "debit": 100.0, "credit": 0.0,
                        "tax_ids": [(6, 0, tax.ids)]}),
                (0, 0, {"account_id": payable.id, "debit": 0.0, "credit": 120.0}),
            ],
        })
        tax_lines = move.line_ids.filtered("tax_line_id")
        self.assertTrue(tax_lines, "an archived tax produced no tax line at all")
        self.assertEqual(
            round(sum(tax_lines.mapped("balance")), 2), 20.0,
            "the archived 20 % tax did not compute 20 % of 100",
        )
        self.assertTrue(
            tax_lines.tax_tag_ids,
            "the tax line carries no tags, so it would report nowhere",
        )
        move.action_post()
        self.assertEqual(move.state, "posted")
