# Copyright 2026 Data Dance s.r.o.
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

from odoo.addons.account.tests.common import AccountTestInvoicingCommon
from odoo.tests import tagged


@tagged("post_install", "-at_install")
class TestCzHistoricVatRates(AccountTestInvoicingCommon):
    """The Czech historical rates.

    The Czech form is *not* rate-agnostic the way the Slovak one is: DPHDP3
    separates the standard rate (lines 01/02, input 40) from the reduced one
    (03/04, input 41). What it does not distinguish is *which* reduced rate --
    15 % and the second-reduced 10 % both reported on 03/04 while they
    coexisted. So cloning is correct precisely because each historical rate is
    cloned from the family it belonged to, which is what these tests pin.

    The chart is loaded by the test rather than assumed to be in the database,
    which also exercises the chart-load hook: the rates below are generated by
    ``_load`` during ``setUpClass``, not by an explicit call.
    """

    chart_template = "cz"

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.company = cls.env.company
        cls.Tax = cls.env["account.tax"].with_context(active_test=False)

    def _historic(self, rate=None):
        domain = [
            ("company_id", "=", self.company.id),
            ("cssk_historic_valid_from", "!=", False),
        ]
        if rate is not None:
            domain.append(("amount", "=", rate))
        return self.Tax.search(domain)

    def _current(self, rate):
        return self.Tax.search([
            ("company_id", "=", self.company.id), ("amount", "=", rate),
            ("cssk_historic_valid_from", "=", False),
        ])

    def _settle(self):
        """Generate once, so the set of source taxes is not still moving.

        The accounting test fixture creates a few taxes of its own AFTER the
        chart is loaded, and therefore after the chart-load hook has run. Those
        legitimately have no historical twin yet, so a count or an idempotency
        check taken straight from ``setUpClass`` would be measuring the fixture
        rather than this module. Settling first is what makes the assertions
        about the generator.
        """
        return self.company._cssk_create_historic_vat_taxes()


    def test_loading_the_chart_generates_them(self):
        """Nobody has to remember to ask.

        A migration project's companies are created *after* the modules are
        installed, so a post-install hook alone would have missed exactly the
        companies the feature exists for.
        """
        self.assertTrue(
            self._historic(),
            "loading the Czech chart should have generated the historical "
            "rates without an explicit call",
        )

    def test_each_rate_is_cloned_from_the_family_it_belonged_to(self):
        """The rule the whole design rests on for CZ.

        20 % was a standard rate and must report on lines 01/02; 15 % was a
        reduced rate and must report on 03/04. Cloning 15 % from the 21 %
        family would file every 2013-2023 reduced supply as a standard one —
        the amount right and the return wrong, which is the failure nobody
        notices until the tax office does.
        """
        self._settle()
        for rate, expected_source in ((20.0, 21.0), (19.0, 21.0),
                                      (15.0, 12.0), (14.0, 12.0),
                                      (10.0, 12.0), (9.0, 12.0), (5.0, 12.0)):
            taxes = self._historic(rate)
            self.assertTrue(taxes, "no %g%% taxes were generated" % rate)
            self.assertEqual(
                set(taxes.mapped("cssk_historic_source_tax_id.amount")),
                {expected_source},
                "%g%% must be cloned from the %g%% family, because that is "
                "what decides whether it reports as standard or reduced"
                % (rate, expected_source),
            )

    def test_the_whole_family_is_generated_not_just_the_plain_rate(self):
        """A rate is not one tax — the CZ chart has EU, EX, RC and ND variants."""
        self._settle()
        current = self._current(12.0)
        self.assertTrue(current, "the 12 % family must exist to be cloned from")
        self.assertEqual(
            len(self._historic(15.0)), len(current),
            "every current reduced-rate tax needs a 15 % twin",
        )
        self.assertIn(
            "15% RC", set(self._historic(15.0).mapped("name")),
            "§ 92a domestic reverse charge",
        )

    def test_a_historic_rate_is_archived(self):
        """It must exist without appearing anywhere somebody raises a document."""
        historic = self._historic()
        self.assertTrue(historic)
        self.assertFalse(any(historic.mapped("active")))
        self.assertFalse(
            self.env["account.tax"].search([("id", "in", historic.ids)]),
            "an ordinary search must not return an archived rate",
        )

    def test_the_clone_keeps_the_tags_that_make_it_report(self):
        """A rate with no tags computes a number and reports it nowhere."""
        self._settle()
        checked = 0
        for tax in self._historic():
            source = tax.cssk_historic_source_tax_id
            self.assertTrue(source, "a generated rate must name what it came from")
            for field in ("invoice_repartition_line_ids",
                          "refund_repartition_line_ids"):
                mine = tax[field].filtered(lambda r: r.repartition_type == "tax")
                theirs = source[field].filtered(
                    lambda r: r.repartition_type == "tax")
                self.assertEqual(
                    [sorted(x.tag_ids.mapped("name")) for x in mine],
                    [sorted(x.tag_ids.mapped("name")) for x in theirs],
                    "%s does not carry its source's tags" % tax.name,
                )
                self.assertEqual(
                    mine.mapped("factor_percent"),
                    theirs.mapped("factor_percent"),
                    "%s changed the repartition split — on a §92a reverse "
                    "charge that is the +100/-100 pair" % tax.name,
                )
            checked += 1
        self.assertTrue(checked, "nothing was actually checked")

    def test_running_twice_creates_nothing_and_clones_no_clones(self):
        """Idempotent: this runs on every module upgrade and every chart load."""
        self._settle()
        before = self._historic()
        self._settle()
        after = self._historic()
        self.assertEqual(set(before.ids), set(after.ids))
        self.assertFalse(
            after.filtered(
                lambda t: t.cssk_historic_source_tax_id.cssk_historic_valid_from
            ),
            "a historical rate was cloned from another historical rate",
        )

    def test_a_hand_made_rate_is_adopted_rather_than_duplicated(self):
        """The state the Czech reference company was actually in.

        Six rates at 15 % and 10 % created ad hoc for one import, active and
        unmarked. Two identical-looking taxes would be worse than none: the
        mapping picks one and the reports read the other.
        """
        self._historic().unlink()
        self.assertFalse(self._historic(), "starting from no generated rates")
        source = self._current(12.0).filtered(
            lambda t: t.type_tax_use == "purchase" and t.name == "12% G"
        )[:1]
        self.assertTrue(source, "expected a 12% G purchase tax")
        handmade = source.copy({"name": "15% G", "amount": 15.0})
        self.assertTrue(handmade.active)

        self.company._cssk_create_historic_vat_taxes()

        same = self.Tax.search([
            ("company_id", "=", self.company.id), ("name", "=", "15% G"),
            ("type_tax_use", "=", "purchase"),
        ])
        self.assertEqual(
            same, handmade,
            "the hand-made rate should have been adopted, leaving exactly one",
        )
        self.assertFalse(handmade.active)
        self.assertEqual(handmade.cssk_historic_valid_from.year, 2013)
        self.assertEqual(handmade.cssk_historic_valid_to.year, 2023)
        self.assertEqual(handmade.cssk_historic_source_tax_id, source)
