# Copyright 2026 Data Dance s.r.o.
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

import re

from odoo import Command, models


def _digits(value, size=10):
    return re.sub(r"\D", "", value or "")[-size:]


class AccountEdiXmlISDOC(models.AbstractModel):
    _inherit = "account.edi.xml.isdoc"

    def _import_fill_invoice(self, invoice, tree, qty_factor):
        logs = super()._import_fill_invoice(invoice, tree, qty_factor)
        if invoice.move_type not in ("in_invoice", "in_refund"):
            return logs
        doc_type = (tree.findtext(self._q("DocumentType")) or "").strip()
        if doc_type == "4":
            logs += self._isdoc_import_proforma_advance(invoice, tree)
        elif doc_type in ("5", "6"):
            logs += self._isdoc_import_advance_tax_document(invoice, tree)
        return logs

    def _import_invoice_ubl_cii(self, invoice, file_data, new=False):
        res = super()._import_invoice_ubl_cii(invoice, file_data, new=new)
        # account rewrites must run AFTER the whole import settles: the
        # payment-term lines are regenerated by the dynamic-line sync, so a
        # rewrite inside _import_fill_invoice would be lost
        tree = file_data.get("xml_tree") if isinstance(file_data, dict) else None
        if tree is not None and invoice.move_type in ("in_invoice", "in_refund"):
            doc_type = (tree.findtext(self._q("DocumentType")) or "").strip()
            if doc_type in ("5", "6"):
                advance, how = self._isdoc_find_advance_order(invoice, tree)
                if advance:
                    invoice.advance_purchase_order_id = advance
                    invoice.message_post(body=self.env._(
                        "ISDOC advance tax document: linked to received "
                        "advance %(order)s (matched by %(how)s).",
                        order=advance.name, how=how,
                    ))
                else:
                    invoice.message_post(body=self.env._(
                        "ISDOC advance tax document: no unique matching "
                        "received advance found — link it manually."
                    ))
                self._isdoc_apply_advance_accounts(invoice)
        return res

    def _isdoc_apply_advance_accounts(self, invoice):
        company = invoice.company_id
        advance = invoice.advance_purchase_order_id
        net_account = (
            company.advance_paid_account_lt_id
            if advance and advance.advance_invoice_long_term
            and company.advance_paid_account_lt_id
            else company.advance_paid_account_id
        )
        if net_account:
            invoice.invoice_line_ids.filtered(
                lambda line: line.display_type == "product"
            ).account_id = net_account
        clearing = company.advance_paid_clearing_account_id
        if clearing:
            invoice.line_ids.filtered(
                lambda line: line.display_type == "payment_term"
            ).account_id = clearing

    # ------------------------------------------------------------------
    # DocumentType 4 — zálohová faktura (non-tax proforma)
    # ------------------------------------------------------------------
    def _isdoc_import_proforma_advance(self, invoice, tree):
        q = self._q
        gross = tree.findtext(
            f'{q("LegalMonetaryTotal")}/{q("TaxInclusiveAmount")}'
        ) or tree.findtext(f'{q("LegalMonetaryTotal")}/{q("PayableAmount")}')
        try:
            gross_amount = float(gross)
        except (TypeError, ValueError):
            return [self.env._(
                "ISDOC proforma (DocumentType 4): could not read the "
                "document total; no received advance was created."
            )]
        product = self.env.ref(
            "account_edi_isdoc_purchase_advance.product_imported_advance"
        )
        order = self.env["purchase.order"].create({
            "partner_id": invoice.partner_id.id,
            "company_id": invoice.company_id.id,
            "currency_id": invoice.currency_id.id,
            "is_advance_invoice": True,
            "partner_ref": invoice.ref or False,
            "order_line": [
                Command.create({
                    "product_id": product.id,
                    "name": self.env._(
                        "Advance per %s", invoice.ref or "ISDOC"
                    ),
                    "product_qty": 1,
                    "price_unit": gross_amount,
                    "tax_ids": [Command.clear()],
                })
            ],
        })
        invoice.advance_purchase_order_id = order
        invoice.message_post(body=self.env._(
            "This ISDOC is a proforma advance invoice (DocumentType 4) — "
            "it must not be posted as a vendor bill. Received advance "
            "%s was created; pay and track it there, then delete this "
            "draft.", order.name,
        ))
        return [self.env._(
            "ISDOC proforma (DocumentType 4): received advance %s created "
            "over %s %s. Do not post this draft bill.",
            order.name, f"{gross_amount:.2f}", invoice.currency_id.name,
        )]

    # ------------------------------------------------------------------
    # DocumentType 5/6 — daňový doklad k přijaté platbě (+ its refund)
    # ------------------------------------------------------------------
    def _isdoc_import_advance_tax_document(self, invoice, tree):
        """Journal and tax-point routing; the advance matching and account
        rewrites run later in _import_invoice_ubl_cii, once the amounts and
        dynamic lines are final."""
        company = invoice.company_id
        journal = company.advance_purchase_journal_id
        if journal and invoice.journal_id != journal:
            invoice.journal_id = journal
        tax_point = tree.findtext(self._q("TaxPointDate"))
        if tax_point and "taxable_supply_date" in invoice._fields:
            invoice.taxable_supply_date = tax_point
        return [self.env._(
            "ISDOC advance tax document (DocumentType %s) — routed to the "
            "advance journal.",
            (tree.findtext(self._q("DocumentType")) or "").strip(),
        )]

    def _isdoc_find_advance_order(self, invoice, tree):
        """Unique open received advance for this document, or (None, "").
        Precedence: supplier's order/original-document reference naming the
        advance, then variable symbol digits, then a single candidate whose
        paid amount equals the document total. Ambiguity bails out."""
        q = self._q
        candidates = self.env["purchase.order"].search([
            ("company_id", "=", invoice.company_id.id),
            ("is_advance_invoice", "=", True),
            ("partner_id", "child_of",
             invoice.partner_id.commercial_partner_id.id),
            ("state", "not in", ("cancel",)),
        ])
        if not candidates:
            return None, ""
        references = [
            tree.findtext(
                f'{q("OrderReferences")}/{q("OrderReference")}'
                f'/{q("ExternalOrderID")}'
            ),
            tree.findtext(
                f'{q("OriginalDocumentReferences")}'
                f'/{q("OriginalDocumentReference")}/{q("ID")}'
            ),
        ]
        for reference in filter(None, references):
            matched = candidates.filtered(
                lambda o: o.name == reference.strip()
            )
            if len(matched) == 1:
                return matched, self.env._("order reference")
        var_symbol = _digits(tree.findtext(
            f'{q("PaymentMeans")}/{q("Payment")}/{q("Details")}'
            f'/{q("VariableSymbol")}'
        ))
        if var_symbol:
            matched = candidates.filtered(
                lambda o: _digits(o.name).lstrip("0")
                == var_symbol.lstrip("0")
            )
            if len(matched) == 1:
                return matched, self.env._("variable symbol")
        waiting = candidates.filtered(
            lambda o: o.advance_invoice_accounting_status == "waiting"
            and o.currency_id.compare_amounts(
                o.amount_paid, invoice.amount_total
            ) == 0
        )
        if len(waiting) == 1:
            return waiting, self.env._("paid amount")
        return None, ""
