# Copyright 2026 Data Dance s.r.o.
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

from odoo import fields, models


class AccountTax(models.Model):
    _inherit = "account.tax"

    l10n_cz_vat_status_source_id = fields.Many2one(
        "account.tax", string="Plátce tax", copy=False, index="btree_not_null",
        ondelete="cascade",
        help="The tax this one stands in for while the company is not a VAT "
        "payer. Generated by l10n_cz_vat_status; a document dated in a plátce "
        "period gets this source tax back.")
    l10n_cz_vat_status_kind = fields.Selection(
        [("nondeductible", "No deduction (VAT to cost)"),
         ("selfassessed", "Self-assessed, no deduction (identifikovaná osoba)")],
        string="Non-payer variant", copy=False)
